scalar-labs/scalardb-samples

scalardb-server-sample/docker-compose-cassandra.yml

I think the correct host and port parameter format for `wait-for-it.sh` is `host:port`, but we specify `tcp://cassandra:9042` in `scalardb-server-sample/docker-compose-cassandra.yml`.  This PR fixes this. Please take a look!

Fix host and port parameter format for wait-for-it.sh

---

microservice-transaction-sample/build.gradle
microservice-transaction-sample/customer-service-schema-loader/Dockerfile
microservice-transaction-sample/order-service-schema-loader/Dockerfile

This PR upgrades the Scalar DB version to `3.4.1` for Microservice Transaction Sample. Please take a look!

Update Microservice Transaction Sample

---

scalardb-graphql-sample/.gitignore
scalardb-graphql-sample/.prettierrc
scalardb-graphql-sample/README.md
scalardb-graphql-sample/codegen.yml
scalardb-graphql-sample/database.properties
scalardb-graphql-sample/docker-compose.yml
scalardb-graphql-sample/emoney-schema.json
scalardb-graphql-sample/graphql/account.graphql
scalardb-graphql-sample/graphql/account_pay.graphql
scalardb-graphql-sample/package-lock.json
scalardb-graphql-sample/package.json
scalardb-graphql-sample/src/emoney.ts
scalardb-graphql-sample/src/generated/graphql.ts
scalardb-graphql-sample/tsconfig.json
scalardb-graphql-sample/wait-for-it.sh

This PR adds a sample GraphQL application to the scalardb-samples repo.
This app is an "emoney" app that has the same features as [scalardb-server-sample](https://github.com/scalar-labs/scalardb-samples/tree/main/scalardb-server-sample), but it has only a transactional table example for simplicity.
The app is composed of a Cassandra database and a GraphQL server running on Docker, and a client app built with Node.js that communicates with the server.

Add a sample GraphQL application

---

microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
multi-storage-transaction-sample/src/main/java/sample/Sample.java
scalardb-sample/src/main/java/sample/Sample.java

Noticed some ScalarDB sample projects use variable name `updatedCreditLimit`, but `updatedCreditTotal` seems better.

Rename `updatedCreditLimit` to `updatedCreditTotal`

---

spring-data-multi-storage-transaction-sample/README.md
spring-data-sample/README.md

We decided the official product name of the integration of Spring Data and ScalarDB. This PR uses the official name  "Spring Data JDBC for ScalarDB" in the 2 sample applications.

Use official product name "Spring Data for ScalarDB" in the sample applications

---

microservice-transaction-sample/gradle/wrapper/gradle-wrapper.properties
multi-storage-transaction-sample/gradle/wrapper/gradle-wrapper.properties
scalardb-sample/gradle/wrapper/gradle-wrapper.properties
scalardb-server-sample/gradle/wrapper/gradle-wrapper.properties
scalardb-sql-jdbc-sample/gradle/wrapper/gradle-wrapper.properties
spring-data-multi-storage-transaction-sample/gradle/wrapper/gradle-wrapper.properties
spring-data-sample/gradle/wrapper/gradle-wrapper.properties

This PR updates the version of Gradle.
I faced the following error when I ran the samples by using Java 17 in spite of almost samples stating `Java (OpenJDK 8 or higher)` as a requirement.
<details>
<summary>Error</summary>
```console
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
```
```console
FAILURE: Build failed with an exception.
* Where:
Settings file '/scalardb-samples/scalardb-sample/settings.gradle'
* What went wrong:
Could not compile settings file '/scalardb-samples/scalardb-sample/settings.gradle'.
> startup failed:
General error during conversion: Unsupported class file major version 61
java.lang.IllegalArgumentException: Unsupported class file …
```

Update gradle version to support latest Java version

---

README.md

This PR adds the [Spring Data JDBC for ScalarDB with microservice transaction sample](https://github.com/scalar-labs/scalardb-samples/tree/main/spring-data-microservice-transaction-sample) to the repository's top-level README.

Add "Spring Data JDBC for ScalarDB with microservice transaction" sample to top-level README

---

microservice-transaction-sample/build.gradle
multi-storage-transaction-sample/build.gradle
scalardb-sample/build.gradle
scalardb-server-sample/build.gradle
scalardb-sql-jdbc-sample/build.gradle
spring-data-multi-storage-transaction-sample/build.gradle
spring-data-sample/build.gradle

This PR updates the ScalarDB dependencies in the samples to version `3.9.1`. The update for the microservice sample application with Spring Data JDBC for ScalarDB is already addressed in https://github.com/scalar-labs/scalardb-samples/pull/42, so this PR focuses on the other samples. Please take a look!

Use ScalarDB 3.9.1

---

spring-data-microservice-transaction-sample/build.gradle
spring-data-microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
spring-data-microservice-transaction-sample/customer-service/src/main/java/sample/customer/domain/repository/CustomerRepository.java
spring-data-microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
spring-data-microservice-transaction-sample/order-service/src/main/java/sample/order/domain/repository/ItemRepository.java
spring-data-microservice-transaction-sample/order-service/src/main/java/sample/order/domain/repository/OrderRepository.java

We've merged [Add some high-level 2PC API for participants](https://github.com/scalar-labs/scalardb-sql/pull/210) and released it as `3.9.1`. The new APIs are useful and should be introduced in the sample application.
This PR update `spring-data-microservice-transaction-sample` to use the new high-level 2PC APIs.

Use new high-level 2PC API in the sample application for microservice with Spring Data JDBC for ScalarDB

---

spring-data-microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
spring-data-microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
spring-data-multi-storage-transaction-sample/src/main/java/sample/SampleService.java
spring-data-sample/src/main/java/sample/SampleService.java

We noticed the current sample projects does unnecessary retries (e.g., the participant service retries by itself when it fails although the retry should be triggered by the coordinator)
This PR replaces the very coarse `@Retryable` annotation for all the methods of a service class with fine-grained annotations on methods to be retried.

Improve the usage of @Retryable in the sample applications of Spring Data JDBC for ScalarDB

---

scalardb-analytics-postgresql-sample/README.md

This PR contains the following minor changes:
- Removes the .md extension from a link. (This caused readers on the docs site to be directed to the raw Markdown file instead of a formatted page.)
- Fixes links to point to `latest` version of docs (originally pointed to `3.9`).

Fix links in documentation

---

scalardb-server-sample/README.md

This PR changes the link for the "Getting Started with ScalarDB" doc, which we updated in https://github.com/scalar-labs/scalardb/pull/990. The previous doc no longer exists, so that's why we need to update this link.

Change link for "Getting Started with ScalarDB"

---

microservice-transaction-sample/README.md
multi-storage-transaction-sample/README.md

This PR revises the ScalarDB tutorials for:
- Creating a sample application that supports multi-storage transactions.
- Creating a sample application that supports microservice transactions.
Related to https://github.com/scalar-labs/scalardb-samples/pull/49
- Revised both tutorials, adding headings and providing additional context to the instructions.
> **Note**
> 
> Many of the formatting and editorial changes in this sample tutorial are similar to the changes I recently made to the "Create a Sample Application by Using ScalarDB" tutorial in https://github.com/scalar-labs/scalardb-samples/pull/49.
- `main`
I built our docs site locally and confirmed that these two sample tutorials, including headings and notice blocks, appeared as expected.
N/A
N/A

Revise sample tutorials for multi-storage transactions and microservice transactions

---

.github/pull_request_template.md

This PR removes the `## Release note` section since we don't need it when submitting PRs in this repository.
Related to https://github.com/scalar-labs/scalardb-samples/pull/51 (I hadn't noticed a [comment](https://github.com/scalar-labs/scalardb-samples/pull/51#issuecomment-1742984854) about removing this section in the original PR.)
Removed the `## Release note` section.
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.
N/A

Remove `Release note` section in PR template

---

microservice-transaction-sample/README.md
microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
microservice-transaction-sample/rpc/src/main/grpc/sample/rpc/CustomerServiceGrpc.java
microservice-transaction-sample/rpc/src/main/java/sample/rpc/GetCustomerInfoRequest.java
microservice-transaction-sample/rpc/src/main/java/sample/rpc/GetCustomerInfoRequestOrBuilder.java
microservice-transaction-sample/rpc/src/main/java/sample/rpc/Sample.java
microservice-transaction-sample/rpc/src/main/proto/sample.proto
spring-data-microservice-transaction-sample/README.md
spring-data-microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
spring-data-microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
spring-data-microservice-transaction-sample/rpc/src/main/grpc/sample/rpc/CustomerServiceGrpc.java
spring-data-microservice-transaction-sample/rpc/src/main/java/sample/rpc/GetCustomerInfoRequest.java
spring-data-microservice-transaction-sample/rpc/src/main/java/sample/rpc/GetCustomerInfoRequestOrBuilder.java
spring-data-microservice-transaction-sample/rpc/src/main/java/sample/rpc/Sample.java
spring-data-microservice-transaction-sample/rpc/src/main/proto/sample.proto

The current micro-service samples call `CustomerService.getCustomerInfo` endpoint from `OrderService.getOrder(s)` endpoints as a separate transaction without using 2PC interface. As a result, 2 or more transactions are created when invoking `CustomerService.getCustomerInfo` endpoint.
This behavior may be good in terms of performance. But there are the following concerns:
1. Strictly speaking, the operations of `CustomerService.getCustomerInfo` is supposed to be a part of the global transaction starting with `OrderService.getOrder(s)`. So, creating 2 or more transaction ID in the coordinator table might be unexpected.
2. If users who develop their application based on this sample adds write operation in `CustomerService.getCustomerInfo` or `OrderService.getOrder(s)`, it might cause …

Microservice samples should call `CustomerService.getCustomerInfo` in a global transaction

---

README.md
microservice-transaction-sample/README.md
multi-storage-transaction-sample/README.md
scalardb-analytics-postgresql-sample/README.md
scalardb-graphql-sample/README.md
scalardb-sample/README.md
scalardb-server-sample/README.md
scalardb-sql-jdbc-sample/README.md
spring-data-microservice-transaction-sample/README.md
spring-data-multi-storage-transaction-sample/README.md
spring-data-sample/README.md

This PR adds a cautionary notice to the top of docs in the `docs` folder. Since those docs should now be updated in the [scalar-labs/docs-internal-scalardb](https://github.com/scalar-labs/docs-internal-scalardb) repository, the cautionary notice that I've added here is to provide guidance for those who may not know where to update the docs.
- https://github.com/scalar-labs/docs-internal-scalardb/pull/15
- Added a cautionary notice to the top of each doc in the `docs` folder, stating that the doc should be updated in the [scalar-labs/docs-internal-scalardb](https://github.com/scalar-labs/docs-internal-scalardb) repository.
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the …

Add notice about the relocation of docs

---

scalardb-sample/database.properties
scalardb-sample/docker-compose.yml

This PR adds some databases to ScalarDB Sample.
N/A
- Added Oracle Database and SQL Server to `database.properties` and `docker-compose.yml` in ScalarDB Sample.
N/A

Add databases to ScalarDB Sample

---

microservice-transaction-sample/docker-compose.yml
multi-storage-transaction-sample/docker-compose.yml
scalardb-analytics-postgresql-sample/docker-compose.yml
scalardb-analytics-spark-sample/docker-compose.yml
scalardb-cluster-standalone-mode/docker-compose.yaml
scalardb-sample/docker-compose.yml
spring-data-microservice-transaction-sample/docker-compose.yml
spring-data-multi-storage-transaction-sample/docker-compose.yml

This PR removes the version element in Docker Compose files since it's obsolete. This was discussed in the comment https://github.com/scalar-labs/scalardb-samples/pull/65#discussion_r1690610604.
N/A
- Removed the version element in Docker Compose files.
N/A

Remove version element in Docker Compose files

---

scalardb-cluster-standalone-mode/docker-compose.yaml
scalardb-cluster-standalone-mode/scalardb-cluster-node.properties

This PR enables GraphQL and SQL in the docker compose file of the ScalarDB Cluster standalone mode.
N/A
N/A

Enable GraphQL and SQL in ScalarDB Cluster standalone mode

---

microservice-transaction-sample/client/build.gradle
microservice-transaction-sample/customer-service/build.gradle
microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
microservice-transaction-sample/customer-service/src/main/java/sample/customer/model/Customer.java
microservice-transaction-sample/order-service/build.gradle
microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
microservice-transaction-sample/order-service/src/main/java/sample/order/model/Item.java
microservice-transaction-sample/order-service/src/main/java/sample/order/model/Order.java
microservice-transaction-sample/order-service/src/main/java/sample/order/model/Statement.java
microservice-transaction-sample/rpc/build.gradle
multi-storage-transaction-sample/build.gradle
multi-storage-transaction-sample/src/main/java/sample/Sample.java
scalardb-kotlin-sample/build.gradle.kts
scalardb-kotlin-sample/src/main/kotlin/sample/ElectronicMoney.kt
scalardb-sample/build.gradle
scalardb-sample/src/main/java/sample/Sample.java
scalardb-sql-jdbc-sample/build.gradle
spring-data-microservice-transaction-sample/client/build.gradle
spring-data-microservice-transaction-sample/customer-service/build.gradle
spring-data-microservice-transaction-sample/order-service/build.gradle
spring-data-microservice-transaction-sample/rpc/build.gradle
spring-data-multi-storage-transaction-sample/build.gradle
spring-data-sample/build.gradle

This PR replaces deprecated Gradle/ScalarDB features to suppress warning messages.
The sample applications of ScalarDB use some deprecated Gradle features and `put` API of ScalarDB. Due to these reasons, multiple warning messages are displayed when the sample application is executed, which is annoying to users.
So this PR replaces all deprecated Gradle features and replaces `put` API of ScalarDB with `update`/`insert`.
N/A
- Replace deprecated Gradle features.
- Replace `put` API of ScalarDB with `update`/`insert`.
N/A

Replace deprecated Gradle/ScalarDB features
