- scalardb-server-sample/README.md
- scalardb-server-sample/build.gradle
- scalardb-server-sample/docker-compose-cassandra.yml
- scalardb-server-sample/docker-compose.yml
- scalardb-server-sample/settings.gradle
- scalardb-server-sample/src/main/java/example/command/ElectronicMoneyCommand.java
- scalardb-server-sample/src/main/java/example/service/ElectronicMoneyWithStorage.java
- scalardb-server-sample/src/main/java/example/service/ElectronicMoneyWithTransaction.java
This PR upgrades the Scalar DB version and changes to use the new schema loader for the Scalar DB Server Sample. Please take a look!
> Update Scalar DB Server Sample

- README.md
> Add GraphQL sample index to README

- scalardb-sample/README.md
- scalardb-sample/build.gradle
- scalardb-sample/docker-compose.yml
- scalardb-sample/src/main/java/sample/Sample.java
> Use Scalar DB 3.6.0 in Scalar DB sample

- multi-storage-transaction-sample/README.md
- multi-storage-transaction-sample/build.gradle
- multi-storage-transaction-sample/docker-compose.yml
- multi-storage-transaction-sample/settings.gradle
- multi-storage-transaction-sample/src/main/java/sample/Sample.java
> Use Scalar DB 3.6.0 in Multi-storage Transaction Sample

- scalardb-server-sample/docker-compose-cassandra.yml
- scalardb-server-sample/docker-compose.yml
We should bind the config file to the `database.properties.tmpl` instead of `database.properties`. This PR is made to fix it. PTAL! Thank you!
> Fix wrong binding for scalardb config in the compose files

- README.md
- microservice-transaction-sample/README.md
- multi-storage-transaction-sample/README.md
- scalardb-graphql-sample/README.md
- scalardb-sample/README.md
- scalardb-server-sample/README.md
This PR renames `Scalar DB` to `ScalarDB`. Please take a look!
> Rename Scalar DB to ScalarDB

- spring-data-sample/src/main/java/sample/SampleApp.java
- spring-data-sample/src/main/java/sample/SampleService.java
- spring-data-sample/src/main/java/sample/command/GetCustomerInfoCommand.java
- spring-data-sample/src/main/java/sample/command/GetOrderCommand.java
- spring-data-sample/src/main/java/sample/command/GetOrdersCommand.java
- spring-data-sample/src/main/java/sample/command/LoadInitialDataCommand.java
- spring-data-sample/src/main/java/sample/command/PlaceOrderCommand.java
- spring-data-sample/src/main/java/sample/command/RepaymentCommand.java
- spring-data-sample/src/main/java/sample/command/SampleCommand.java
This is a follow-up PR for https://github.com/scalar-labs/scalardb-samples/pull/22/files/d243227426599a8408b4a896b353a22582b77f17#r1122529454
> Spring Data sample: Add private keyword on @Autowired variables

- spring-data-sample/README.md
This is a followup PR for https://github.com/scalar-labs/scalardb-samples/pull/19. I think there is room to improve README and this PR handles it.
> Spring Data sample: small README update

- spring-data-sample/database.properties
This is just a cleanup of unused config file https://github.com/scalar-labs/scalardb-samples/pull/22#discussion_r1122598484.
> Spring Data sample: Remove unused config file

- microservice-transaction-sample/README.md
- microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
This PR modifies the README of the Microservices Transaction Sample to reflect the changes made in https://github.com/scalar-labs/scalardb-samples/pull/29. Please take a look!
> Revise README in Microservice Transaction Sample

- scalardb-sample/README.md
- scalardb-sample/database-docker.properties
- scalardb-sample/docker-compose.yml
This PR revises the ScalarDB Sample. I'll add inline comments for the details. Please take a look!
> Revise ScalarDB Sample

- scalardb-graphql-sample/README.md
- scalardb-graphql-sample/database.properties
- scalardb-graphql-sample/docker-compose.yml
- scalardb-graphql-sample/graphql-server-database.properties
> Use Schema Loader jar to load schema in ScalarDB GraphQL Sample

- scalardb-sql-jdbc-sample/README.md
- spring-data-multi-storage-transaction-sample/README.md
- spring-data-sample/README.md
I realized that I overlooked including this way in the previous PR. This PR now includes it. Please take a look!
> Add another way to specify GitHub username and personal access token with environment variables to SQL samples

- spring-data-microservice-transaction-sample/README.md
Some suggestions from @josh-wong were dropped from the PR merge due to a timing issue. I also think there are some sentences we should apply the same change.
This PR applies the following suggestions in the previous PR and also applies the same change for other sentences.
- https://github.com/scalar-labs/scalardb-samples/pull/37#discussion_r1237925642
- https://github.com/scalar-labs/scalardb-samples/pull/37#discussion_r1237925805
- https://github.com/scalar-labs/scalardb-samples/pull/37#discussion_r1237926605
- https://github.com/scalar-labs/scalardb-samples/pull/37#discussion_r1237926795
- https://github.com/scalar-labs/scalardb-samples/pull/37#discussion_r1237927425
- https://github.com/scalar-labs/scalardb-samples/pull/37#discussion_r1237927566
- …
> Revise README of Spring Data JDBC for ScalarDB with microservice

- microservice-transaction-sample/README.md
- microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
- microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
This PR revises the Microservice Transaction Sample, with a particular focus on exception handling. Please take a look!
> Revise Microservice Transaction Sample for exception handling

- microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerService.java
- microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerServiceServer.java
- microservice-transaction-sample/order-service/src/main/java/sample/order/OrderService.java
- microservice-transaction-sample/order-service/src/main/java/sample/order/OrderServiceServer.java
- scalardb-server-sample/src/main/java/sample/ElectronicMoney.java
- scalardb-server-sample/src/main/java/sample/ElectronicMoneyWithStorage.java
- spring-data-microservice-transaction-sample/customer-service/src/main/java/sample/customer/CustomerServiceServer.java
- spring-data-microservice-transaction-sample/order-service/src/main/java/sample/order/OrderServiceServer.java
**Changes**
This updates the exception and logs messages style so that : 
- the first character is capitalized 
- the message should not end with punctuation
> Harmonize exception and logs messages style

- scalardb-sample/README.md
This PR revises the basic sample tutorial that shows users how to create an application that uses ScalarDB. 
> **Note**
> 
> Many of the formatting and editorial changes in this sample tutorial are similar to the changes I recently made to the "Getting Started with ScalarDB" doc in https://github.com/scalar-labs/scalardb/pull/1028.
N/A
- Revised the tutorial, adding headings and providing additional context to the instructions.
- `master`
I ran our docs site locally and confirmed that this sample tutorial, including headings and notice blocks, appeared as expected.
Please see my comments in the doc.
> Revise basic ScalarDB sample

- microservice-transaction-sample/README.md
- multi-storage-transaction-sample/README.md
- scalardb-sample/README.md
This PR contains some minor fixes to sample tutorials.
N/A
- Fix broken link that points to the ScalarDB sample tutorial.
- Fix heading indentation.
- Change heading title for consistency with other sample tutorials.
> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.
N/A
N/A
> Fix broken links, headings, and formatting for consistency

- microservice-transaction-sample/README.md
- microservice-transaction-sample/rpc/build.gradle
This PR fixes document bugs in the sample application for the `Microservice Transaction Sample` application.
N/A
* Update the args of the `docker-compose` command.
* Update supported Java versions.
N/A
> Fix document bug in microservice-transaction-sample

- scalardb-sample/build.gradle
- scalardb-sample/database.properties
- scalardb-sample/docker-compose.yml
This PR updates ScalarDB Sample.
N/A
- Added MySQL, PostgreSQL, and DynamoDB configurations to `docker-compose.yml` so that users can run the database locally easily.
- Added MySQL, PostgreSQL, Cosmos DB, and DynamoDB configurations to `database.properties`.
N/A
> Update ScalarDB Sample

- scalardb-cluster-standalone-mode/docker-compose.yaml
- scalardb-cluster-standalone-mode/scalardb-cluster-node.properties
This PR updates ScalarDB Cluster standalone mode files.
N/A
- Updated ScalarDB Cluster standalone mode files.
N/A
> Update ScalarDB Cluster standalone mode files

- scalardb-cluster-standalone-mode/docker-compose.yaml
- spring-data-multi-storage-transaction-sample/docker-compose.yml
This PR fixes typos in Docker Compose files.
N/A
- Fixed typos in Docker Compose files.
N/A
> Fix typos in Docker Compose files
